spring:
  datasource:
    username: college
    password: college
    url: jdbc:mysql://localhost:3306/college
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  
  sql:
    init:
      mode: never